In [4]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)
a=tf.constant('hello world')
print(a.numpy())

b'hello world'


In [6]:
#scalar constants
a=tf.constant(42)
b=tf.constant(3.12)
c=tf.constant('hello,tensorflow!')
print(a)
print(b)
print(c)

tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor(3.12, shape=(), dtype=float32)
tf.Tensor(b'hello,tensorflow!', shape=(), dtype=string)


In [7]:
#vector constants
a=tf.constant([1,2,3])
b=tf.constant([1.0,2.0,3.0])
print(a)
print(b)
print(a.numpy())
print(b.numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
[1 2 3]
[1. 2. 3.]


In [10]:
#matrix constants
a=tf.constant([[1,2],[3,4]])
print(a)
print(a.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


In [17]:
#higher dimenssion matrix constants
a=tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]])
#print(a)
print(a.numpy())


[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [18]:
a=tf.constant(True)
print(a)
print(a.numpy())

tf.Tensor(True, shape=(), dtype=bool)
True


In [20]:
a=tf.zeros(shape=(3,3))
print(a)
print(a.numpy())

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
a=tf.ones(shape=(3,3))
print(a)
print(a.numpy())

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
a=tf.eye(3)
print(a)
print(a.numpy())

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[2,3],[4,5]])
c=tf.constant(4)
print((a*b).numpy())
print((a*c).numpy())
print((tf.matmul(a,b)).numpy())
print((a@b).numpy())

[[ 2  6]
 [12 20]]
[[ 4  8]
 [12 16]]
[[10 13]
 [22 29]]
[[10 13]
 [22 29]]


In [32]:
a=tf.constant(1.25)
print(a.numpy())
b=tf.cast(a,dtype=tf.int32)
print(b.numpy())

1.25
1


In [35]:
x=tf.constant([[1.,2.,3.],[4.,5.,6.]])
f=tf.concat([x,x,x],axis=1)
print(f.numpy())
f1=tf.concat([x,x,x],axis=0)
print(f1.numpy())

[[1. 2. 3. 1. 2. 3. 1. 2. 3.]
 [4. 5. 6. 4. 5. 6. 4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [46]:
#x=tf.constant([[11.0,12.0,13.0]])
logits=tf.constant([20.0,30.0,40.0,60.0,70.0])
softmax_probs=tf.nn.softmax(logits,axis=-1)
print((softmax_probs).numpy())

[1.9286623e-22 4.2481610e-18 9.3571980e-14 4.5397868e-05 9.9995458e-01]
